### ISSUE TITLE
Error with unit tablespoon

### ISSUE THREAD

**Issue by LeicesterTriangle** [xxv/Units#6]
If it try to convert "1 tbsp" to "ml" I get the following error: 

"Invalid definition of 'tbsp'. Unit 'tablespoon' is unknown."

I can't access the definitions file on thios non-rooted Android...

**Comment by xxv** [comment]
Hello,

Are you outside the united state, UK, or Australia? Because each of those places has a different definition of what tbsp means in volume and so the software adjusts automatically. 

You can use ustablespoon, brtablespoon, or austbsp depending on which country's units are customary for where you are.

What county are you in and what would you expect the volume to be?

-Steve

On June 20, 2021 6:09:29 AM EDT, LeicesterTriangle ***@***.***> wrote:
>If it try to convert "1 tbsp" to "ml" I get the following error: 
>
>"Invalid definition of 'tbsp'. Unit 'tablespoon' is unknown."
>
>I can't access the definitions file on thios non-rooted Android...
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/xxv/Units/issues/6

-Steve

**Comment by LeicesterTriangle** [comment]
Ah, this makes sense! I thought it a very odd error, seeing as the "units" code is pretty mature as far as the GNU/unix implementations go. 
I am indeed outside the US/UK/AUS, and was tripped up by the invalid difinition when using units to convert US recipes. I expect a tablespoon to be ~15 ml -- which I know, but I use it for the "koshersalt" conversion, where the density matters. 
So the correct usage is to use "ustablespoon" or "ustbsp", and then everything does work as expected.
